info:
  component: zuul gateway Server

spring:
  application:
    name: gateway-server
  profiles: container

endpoints:
  restart:
    enabled: true
  

zuul:
  prefix: /api
  routes:
    user:
      path: /user/**
      serviceId: shopping-user-service
    course:
      path: /product/**
      serviceId: shopping-product-service
    log:
      path: /log/**
      serviceId: shopping-log-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000

server:
  port: 8700

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
management:
  endpoint:
    shutdown:
      enabled: true